import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";
import * as XLSX from "xlsx";

import {
    decryptAgileWorkbook,
    isAgileEncryptedWorkbook,
} from "../parser/excelAgileDecryption";

import {
    ExcelPasswordError,
    parseExcel,
    resolveExcelWorkbookContent,
} from "../parser/excelParser";

import { processExcel } from "../pipeline";

// Fixture: a minimal 2-row "Date, Description, Amount" workbook,
// encrypted with ECMA-376 Agile Encryption (SHA512, AES-256 - the
// scheme/parameters current Excel itself defaults to for "Encrypt with
// Password") under the password below. Generated once with a real,
// independent MS-OFFCRYPTO implementation (officecrypto-tool) - not
// produced by this codebase, since neither xlsx@0.18.5 nor this
// package can itself write an encrypted file (see
// excelAgileDecryption.ts's file header) - and never regenerated by
// these tests. This is a completely different (SHA512/256-bit)
// parameter combination from the real bank-statement file this feature
// was built and verified against by hand (which used SHA1/128-bit) -
// together they cover both hash-algorithm/key-size paths this code
// actually branches on (see createHasher/deriveBlockKey).
const FIXTURE_PASSWORD = "test-password-123";

const __dirname = dirname(
    fileURLToPath(import.meta.url)
);

function loadAgileEncryptedFixture(): ArrayBuffer {
    const base64 = readFileSync(
        join(
            __dirname,
            "fixtures",
            "agile-encrypted-sha512.b64.txt"
        ),
        "utf8"
    ).trim();

    const buffer = Buffer.from(base64, "base64");

    return buffer.buffer.slice(
        buffer.byteOffset,
        buffer.byteOffset + buffer.byteLength
    );
}

function createUnprotectedWorkbook(): ArrayBuffer {
    const workbook = XLSX.utils.book_new();

    const sheet = XLSX.utils.aoa_to_sheet([
        ["Date", "Description", "Amount"],
        ["2026-08-01", "Coffee Shop", 250],
    ]);

    XLSX.utils.book_append_sheet(
        workbook,
        sheet,
        "Sheet1"
    );

    return XLSX.write(workbook, {
        type: "array",
        bookType: "xlsx",
    });
}

describe("isAgileEncryptedWorkbook", () => {
    it("detects a real Agile-Encryption-protected .xlsx", () => {
        expect(
            isAgileEncryptedWorkbook(
                loadAgileEncryptedFixture()
            )
        ).toBe(true);
    });

    it("returns false for an ordinary unprotected .xlsx", () => {
        expect(
            isAgileEncryptedWorkbook(
                createUnprotectedWorkbook()
            )
        ).toBe(false);
    });

    it("returns false (never throws) for content that isn't a CFB container at all", () => {
        const garbage = new TextEncoder().encode(
            "not a spreadsheet"
        ).buffer;

        expect(
            isAgileEncryptedWorkbook(garbage)
        ).toBe(false);
    });
});

describe("decryptAgileWorkbook", () => {
    it("decrypts with the correct password and produces a workbook parseExcel can read", async () => {
        const decrypted = await decryptAgileWorkbook(
            loadAgileEncryptedFixture(),
            FIXTURE_PASSWORD
        );

        const document = parseExcel(decrypted);

        expect(document.headers).toEqual([
            "Date",
            "Description",
            "Amount",
        ]);

        expect(document.rows).toHaveLength(1);
        expect(document.rows[0].values).toEqual([
            "2026-08-01",
            "Coffee Shop",
            "250",
        ]);
    });

    it("rejects a wrong password with ExcelPasswordError(reason: incorrect) - never a generic/parse error", async () => {
        await expect(
            decryptAgileWorkbook(
                loadAgileEncryptedFixture(),
                "definitely-the-wrong-password"
            )
        ).rejects.toMatchObject({
            name: "ExcelPasswordError",
            reason: "incorrect",
        });
    });

    it("never leaks the password into the decrypted bytes", async () => {
        const decrypted = await decryptAgileWorkbook(
            loadAgileEncryptedFixture(),
            FIXTURE_PASSWORD
        );

        expect(
            Buffer.from(decrypted).includes(
                FIXTURE_PASSWORD
            )
        ).toBe(false);
    });
});

// resolveExcelWorkbookContent is what ImportService.previewExcel
// actually calls before processExcel/getExcelSheetNames - these tests
// exercise that exact entry point, end to end.
describe("resolveExcelWorkbookContent", () => {
    it("requires a password for a protected file when none is supplied", async () => {
        await expect(
            resolveExcelWorkbookContent(
                loadAgileEncryptedFixture()
            )
        ).rejects.toMatchObject({
            name: "ExcelPasswordError",
            reason: "required",
        });
    });

    it("rejects a wrong password the same way decryptAgileWorkbook does", async () => {
        await expect(
            resolveExcelWorkbookContent(
                loadAgileEncryptedFixture(),
                "definitely-the-wrong-password"
            )
        ).rejects.toMatchObject({
            name: "ExcelPasswordError",
            reason: "incorrect",
        });
    });

    it("with the correct password, returns content processExcel can run the normal pipeline on - preview/mapping/import are unaffected", async () => {
        const resolvedContent =
            await resolveExcelWorkbookContent(
                loadAgileEncryptedFixture(),
                FIXTURE_PASSWORD
            );

        const result = processExcel(
            resolvedContent,
            "Sheet1",
            "BANK_CSV"
        );

        expect(result.mapping.date).toBe("Date");
        expect(result.mapping.description).toBe(
            "Description"
        );
        expect(result.mapping.amount).toBe(
            "Amount"
        );

        expect(result.candidates).toHaveLength(1);
        expect(
            result.candidates[0].transactionDate
        ).toBe("2026-08-01");
        expect(
            result.candidates[0].amount
        ).toBe(250);
    });

    it("returns unprotected content completely unchanged, whether or not a password happens to be supplied - existing behavior preserved", async () => {
        const content = createUnprotectedWorkbook();

        const withoutPassword =
            await resolveExcelWorkbookContent(
                content
            );

        const withPassword =
            await resolveExcelWorkbookContent(
                content,
                "never-needed"
            );

        expect(withoutPassword).toBe(content);
        expect(withPassword).toBe(content);
    });
});

describe("parseExcel alone (bypassing resolveExcelWorkbookContent) is unchanged - the Agile-decrypt capability is purely additive", () => {
    it("still can't decrypt an Agile-protected file on its own, even with the correct password - only XLSX.read's own (unchanged) classification applies here", () => {
        expect(() =>
            parseExcel(loadAgileEncryptedFixture(), {
                password: FIXTURE_PASSWORD,
            })
        ).toThrow(ExcelPasswordError);
    });
});

describe("ExcelPasswordError instances thrown by the Agile path are real ExcelPasswordError instances", () => {
    it("instanceof check passes (not just a same-shaped object)", async () => {
        await expect(
            decryptAgileWorkbook(
                loadAgileEncryptedFixture(),
                "wrong"
            )
        ).rejects.toBeInstanceOf(ExcelPasswordError);
    });
});
