import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { beforeAll, describe, expect, it, vi } from "vitest";

// Regression fixture for a real bug found against a real SBI Credit
// Card PDF statement: the raw text pdf-parse extracts from that exact
// file (anonymized account/card numbers only), captured once and never
// regenerated by these tests - see the same fixtures/ convention used
// by excelAgileDecryption.test.ts. This file uses 2-digit-year dates
// ("16 Jul 26") and single-letter C/D markers instead of Axis's
// "DR"/"CR" - both previously mishandled, in different ways, by the
// universal (bank-agnostic) PDF pipeline; nothing here is SBI-specific
// logic, only a real-world input shape the existing structural rules
// must already cover.
const __dirname = dirname(
    fileURLToPath(import.meta.url)
);

function loadSbiFixtureText(): string {
    return readFileSync(
        join(
            __dirname,
            "fixtures",
            "sbi-credit-card-statement.txt"
        ),
        "utf8"
    );
}

// A second, later real SBI Credit Card statement (same account, next
// billing cycle) - captured the same way. This one exposed a distinct
// bug: several lines carry a parenthetical tax/annotation aside between
// the description and the real trailing amount (e.g.
// "(EXCL TAX 0.00)"), which findTail()'s isAmount() used to mistake for
// the transaction's own amount because it stripped an unmatched closing
// paren in isolation. Nothing here is SBI-specific - any statement
// using this generic parenthetical-aside shape would hit the same bug.
function loadSbiFixtureText2(): string {
    return readFileSync(
        join(
            __dirname,
            "fixtures",
            "sbi-credit-card-statement-2.txt"
        ),
        "utf8"
    );
}

const { mockState } = vi.hoisted(() => ({
    mockState: { text: "" as string | null },
}));

vi.mock("pdf-parse", () => {
    class PDFParse {
        static setWorker(): void {}

        constructor(_options: unknown) {}

        async getText() {
            if (mockState.text === null) {
                throw new Error(
                    "Invalid PDF structure"
                );
            }

            return { text: mockState.text };
        }

        async destroy() {}
    }

    return { PDFParse };
});

import { parsePdf } from "../parser/pdfParser";
import { processPdf } from "../pipeline";

beforeAll(() => {
    vi.stubGlobal("window", {
        location: { origin: "http://localhost" },
    });
});

describe("PDF parser - real SBI Credit Card statement (2-digit years, single-letter C/D markers)", () => {
    it("extracts exactly the 80 real transactions - the bare '04 Sep 2026' summary/total row is not one of them", async () => {
        mockState.text = loadSbiFixtureText();

        const result = await parsePdf(
            new ArrayBuffer(0)
        );

        expect(result.structured).toBe(true);

        // Real statement: 80 dated transaction lines. The Account
        // Summary section's "Payment Due Date" (04 Sep 2026) sits
        // immediately above a bare two-number line (Total Amount Due /
        // current balance) with no description at all between them -
        // exactly the shape that used to be misidentified as an
        // 81st, bogus transaction.
        expect(result.document.rows).toHaveLength(
            80
        );

        expect(
            result.document.rows.some(
                (row) => row.values[0] === "04 Sep 2026"
            )
        ).toBe(false);

        // No row was built with an empty description - the structural
        // safeguard that rejected the summary row must never reject a
        // real transaction's own (possibly short) description either.
        expect(
            result.document.rows.every(
                (row) => row.values[1].length > 0
            )
        ).toBe(true);
    });

    it("preserves 2-digit-year transaction dates exactly as printed", async () => {
        mockState.text = loadSbiFixtureText();

        const result = await parsePdf(
            new ArrayBuffer(0)
        );

        const dates = result.document.rows.map(
            (row) => row.values[0]
        );

        expect(dates).toContain("16 Jul 26");
        expect(dates).toContain("15 Aug 26");

        // Every date is 2-digit-year here - none accidentally promoted
        // to/confused with a 4-digit year, and none dropped.
        expect(
            dates.every((date) =>
                /^\d{1,2} [A-Za-z]{3} \d{2}$/.test(
                    date
                )
            )
        ).toBe(true);
    });

    it("correctly parses a real transaction line using a single-letter 'C' marker - amount and description intact, direction left undetermined rather than guessed from the letter", async () => {
        mockState.text = loadSbiFixtureText();

        const result = await parsePdf(
            new ArrayBuffer(0)
        );

        const paymentReceived =
            result.document.rows.find(
                (row) =>
                    row.values[1] ===
                    "PAYMENT RECEIVED 000000000DUTI6FV1PYEPAD"
            );

        expect(paymentReceived).toBeDefined();
        expect(paymentReceived?.values[0]).toBe(
            "16 Jul 26"
        );
        expect(paymentReceived?.values[2]).toBe(
            "50000.00"
        );
        // Single-letter C/D is not CR/DR - findTail's 3-shape marker
        // check never matches a single letter, so this resolves to the
        // amount-only shape and direction is left blank rather than
        // silently mapping "C"/"D" to credit/debit (that would be a
        // bank/issuer-specific vocabulary rule, which this pipeline
        // deliberately never hardcodes).
        expect(paymentReceived?.values[3]).toBe("");
    });

    it("correctly parses a real transaction line using a single-letter 'D' marker too", async () => {
        mockState.text = loadSbiFixtureText();

        const result = await parsePdf(
            new ArrayBuffer(0)
        );

        const e2e = result.document.rows.find(
            (row) =>
                row.values[1] ===
                "E2E NETWORKS LIMITED BANGALORE IN (Pay in EMIs)" &&
                row.values[0] === "15 Jul 26"
        );

        expect(e2e).toBeDefined();
        expect(e2e?.values[2]).toBe("17700.00");
        expect(e2e?.values[3]).toBe("");
    });

    it("no candidate produced from the full pipeline has an empty payee/description, and all 80 real transactions survive as candidates", async () => {
        mockState.text = loadSbiFixtureText();

        const result = await processPdf(
            new ArrayBuffer(0),
            "CREDIT_CARD_PDF"
        );

        expect(result.candidates).toHaveLength(80);

        const emptyPayeeCandidates =
            result.candidates.filter(
                (candidate) =>
                    !candidate.payee &&
                    !candidate.description
            );

        expect(emptyPayeeCandidates).toHaveLength(0);

        // None of the real transactions should fail validation for a
        // missing payee/description - the one defect that used to
        // reach validation (the bogus summary row) is gone before it
        // gets here at all.
        expect(
            result.validation.errors.some((error) =>
                error.message
                    .toLowerCase()
                    .includes("payee or description")
            )
        ).toBe(false);
    });

    // Structural-discriminator regression: a genuinely non-bank-statement
    // PDF (no date-led transaction lines at all - parsePdf's own
    // extraction finds nothing, so it returns structured: false and
    // falls back to genericDocument's column-split) must still be run
    // through the generic second pass (extractPdfTransactions) via
    // processPdf - only a document pdfParser.ts itself already
    // structured (structured: true) skips it.
    it("still runs the generic fallback extractor for a PDF pdfParser.ts could not structure itself", async () => {
        // No line starts with a date (or a serial number + date), so
        // pdfParser.ts's own structural extraction finds zero
        // transaction blocks and falls back to genericDocument -
        // exactly the "could not structure it" case this branch of
        // processPdf must still hand to extractPdfTransactions.
        mockState.text = [
            "Description\tDate\tDebit\tCredit",
            "ATM Withdrawal\t01/08/2026\t500.00\t",
            "Salary\t05/08/2026\t\t50000.00",
        ].join("\n");

        const parsed = await parsePdf(
            new ArrayBuffer(0)
        );

        expect(parsed.structured).toBe(false);

        const result = await processPdf(
            new ArrayBuffer(0),
            "BANK_CSV"
        );

        expect(result.candidates).toHaveLength(2);
        expect(result.candidates[0]?.amount).toBe(
            500
        );
        expect(result.candidates[1]?.amount).toBe(
            50000
        );
    });
});

describe("PDF parser - real SBI Credit Card statement (parenthetical tax/annotation asides must not be mistaken for the amount)", () => {
    // "16 May 26 FINANCE CHARGE CREDIT (EXCL TAX 0.00) 0.02 C" - the
    // parenthetical's own figure is exactly 0.00, so the old bug (which
    // picked "0.00)" as the amount) failed validation outright: 0.00 is
    // not a valid positive amount, and the real trailing "C" marker was
    // never even reached. This is the row that first surfaced the bug.
    it("FINANCE CHARGE CREDIT: extracts the real trailing amount (0.02), not the parenthetical tax figure (0.00), and produces no validation error", async () => {
        mockState.text = loadSbiFixtureText2();

        const parsed = await parsePdf(
            new ArrayBuffer(0)
        );

        const row = parsed.document.rows.find(
            (r) => r.values[0] === "16 May 26"
        );

        expect(row).toBeDefined();
        expect(row?.values[1]).toBe(
            "FINANCE CHARGE CREDIT (EXCL TAX 0.00)"
        );
        expect(row?.values[2]).toBe("0.02");
        expect(row?.values[2]).not.toBe("0.00");

        const result = await processPdf(
            new ArrayBuffer(0),
            "CREDIT_CARD_PDF"
        );

        const candidate = result.candidates.find(
            (c) =>
                c.description?.startsWith(
                    "FINANCE CHARGE CREDIT",
                ),
        );

        expect(candidate).toBeDefined();
        expect(candidate?.amount).toBe(0.02);
        expect(candidate?.amount).not.toBe(0);

        // No validation error for this row at all - a valid positive
        // amount was found, so the row is a normal, importable
        // transaction like any other.
        expect(
            result.validation.errors.some(
                (error) => error.rowNumber === candidate?.rowNumber,
            ),
        ).toBe(false);

        // Per task scope: C/D is not mapped to a direction by this
        // pipeline (that would be issuer-specific vocabulary) - type
        // is left as whatever the existing universal logic already
        // produces here (undetermined), not asserted as CR/DR.
    });

    // "13 Jun 26 DCC MARKUP FEE DR (EXCL TAX 12.58) 69.90 D" - the
    // parenthetical figure (12.58) is non-zero, so the old bug produced
    // a *silently wrong* amount that still passed validation (a
    // deceptively "ready" row with corrupted data) instead of an
    // obvious error.
    it("DCC MARKUP FEE: extracts the real trailing amount (69.90), not the parenthetical tax figure (12.58)", async () => {
        mockState.text = loadSbiFixtureText2();

        const parsed = await parsePdf(
            new ArrayBuffer(0)
        );

        const row = parsed.document.rows.find(
            (r) => r.values[0] === "13 Jun 26"
                && r.values[1].startsWith("DCC MARKUP FEE"),
        );

        expect(row).toBeDefined();
        expect(row?.values[1]).toBe(
            "DCC MARKUP FEE DR (EXCL TAX 12.58)"
        );
        expect(row?.values[2]).toBe("69.90");
        expect(row?.values[2]).not.toBe("12.58");
    });

    // "15 Jun 26 FIN CHARGE ON RETAIL (EXCL TAX 2299.82) 12,776.76 D" -
    // same bug, largest of the three affected figures, also
    // comma-formatted in the source text.
    it("FIN CHARGE ON RETAIL: extracts the real trailing amount (12776.76), not the parenthetical tax figure (2299.82)", async () => {
        mockState.text = loadSbiFixtureText2();

        const parsed = await parsePdf(
            new ArrayBuffer(0)
        );

        const row = parsed.document.rows.find(
            (r) => r.values[0] === "15 Jun 26"
                && r.values[1].startsWith("FIN CHARGE ON RETAIL"),
        );

        expect(row).toBeDefined();
        expect(row?.values[1]).toBe(
            "FIN CHARGE ON RETAIL (EXCL TAX 2299.82)"
        );
        expect(row?.values[2]).toBe("12776.76");
        expect(row?.values[2]).not.toBe("2299.82");
    });

    it("never selects any of the three parenthetical annotation figures (0.00, 12.58, 2299.82) as a transaction amount anywhere in the document", async () => {
        mockState.text = loadSbiFixtureText2();

        const parsed = await parsePdf(
            new ArrayBuffer(0)
        );

        const amounts = parsed.document.rows.map(
            (r) => r.values[2]
        );

        expect(amounts).not.toContain("0.00");
        expect(amounts).not.toContain("12.58");
        expect(amounts).not.toContain("2299.82");
    });

    it("preserves the valid accounting-style negative-amount parenthesis form, e.g. '(500.00)', as a single self-contained amount", async () => {
        mockState.text = [
            "16 May 26 REFUND ADJUSTMENT (500.00) C",
        ].join("\n");

        const parsed = await parsePdf(
            new ArrayBuffer(0)
        );

        expect(parsed.document.rows).toHaveLength(1);
        expect(
            parsed.document.rows[0]?.values[1]
        ).toBe("REFUND ADJUSTMENT");
        expect(
            parsed.document.rows[0]?.values[2]
        ).toBe("500.00");
    });
});
