import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { beforeAll, describe, expect, it, vi } from "vitest";

// Regression fixture for a real bug found against a real SBI Credit
// Card PDF statement: the raw text pdf-parse extracts from that exact
// file (anonymized account/card numbers only), captured once and never
// regenerated by these tests - see the same fixtures/ convention used
// by excelAgileDecryption.test.ts. This file uses 2-digit-year dates
// ("16 Jul 26") and single-letter C/D markers instead of Axis's
// "DR"/"CR" - both previously mishandled, in different ways, by the
// universal (bank-agnostic) PDF pipeline; nothing here is SBI-specific
// logic, only a real-world input shape the existing structural rules
// must already cover.
const __dirname = dirname(
    fileURLToPath(import.meta.url)
);

function loadSbiFixtureText(): string {
    return readFileSync(
        join(
            __dirname,
            "fixtures",
            "sbi-credit-card-statement.txt"
        ),
        "utf8"
    );
}

// A second, later real SBI Credit Card statement (same account, next
// billing cycle) - captured the same way. This one exposed a distinct
// bug: several lines carry a parenthetical tax/annotation aside between
// the description and the real trailing amount (e.g.
// "(EXCL TAX 0.00)"), which findTail()'s isAmount() used to mistake for
// the transaction's own amount because it stripped an unmatched closing
// paren in isolation. Nothing here is SBI-specific - any statement
// using this generic parenthetical-aside shape would hit the same bug.
function loadSbiFixtureText2(): string {
    return readFileSync(
        join(
            __dirname,
            "fixtures",
            "sbi-credit-card-statement-2.txt"
        ),
        "utf8"
    );
}

const { mockState } = vi.hoisted(() => ({
    mockState: { text: "" as string | null },
}));

vi.mock("pdf-parse", () => {
    class PDFParse {
        static setWorker(): void {}

        constructor(_options: unknown) {}

        async getText() {
            if (mockState.text === null) {
                throw new Error(
                    "Invalid PDF structure"
                );
            }

            return { text: mockState.text };
        }

        async destroy() {}
    }

    return { PDFParse };
});

import { parsePdf } from "../parser/pdfParser";
import { processPdf } from "../pipeline";
import type { NormalizedTransactionCandidate } from "../types";

// Sum of one direction's amounts, in exact cents.
function totalOf(
    candidates: readonly NormalizedTransactionCandidate[],
    type: string,
): number {
    return (
        candidates
            .filter((c) => c.type === type)
            .reduce((sum, c) => sum + Math.round((c.amount ?? 0) * 100), 0) / 100
    );
}

beforeAll(() => {
    vi.stubGlobal("window", {
        location: { origin: "http://localhost" },
    });
});

describe("PDF parser - real SBI Credit Card statement (2-digit years, single-letter C/D markers)", () => {
    it("extracts exactly the 82 real transactions - the bare '04 Sep 2026' summary/total row is not one of them", async () => {
        mockState.text = loadSbiFixtureText();

        const result = await parsePdf(
            new ArrayBuffer(0)
        );

        expect(result.structured).toBe(true);

        // Real statement: 80 dated transaction lines plus 2 undated fee
        // lines (FORGN CURR MARKUP DB, IGST DB). The Account
        // Summary section's "Payment Due Date" (04 Sep 2026) sits
        // immediately above a bare two-number line (Total Amount Due /
        // current balance) with no description at all between them -
        // exactly the shape that used to be misidentified as an
        // 81st, bogus transaction.
        expect(result.document.rows).toHaveLength(
            82
        );

        expect(
            result.document.rows.some(
                (row) => row.values[0] === "04 Sep 2026"
            )
        ).toBe(false);

        // No row was built with an empty description - the structural
        // safeguard that rejected the summary row must never reject a
        // real transaction's own (possibly short) description either.
        expect(
            result.document.rows.every(
                (row) => row.values[1].length > 0
            )
        ).toBe(true);
    });

    it("preserves 2-digit-year transaction dates exactly as printed", async () => {
        mockState.text = loadSbiFixtureText();

        const result = await parsePdf(
            new ArrayBuffer(0)
        );

        const dates = result.document.rows.map(
            (row) => row.values[0]
        );

        expect(dates).toContain("16 Jul 26");
        expect(dates).toContain("15 Aug 26");

        // Every date is 2-digit-year here - none accidentally promoted
        // to/confused with a 4-digit year, and none dropped.
        expect(
            dates.every((date) =>
                /^\d{1,2} [A-Za-z]{3} \d{2}$/.test(
                    date
                )
            )
        ).toBe(true);
    });

    it("correctly parses a real transaction line using a single-letter 'C' marker - amount and description intact, direction read from the trailing marker cell", async () => {
        mockState.text = loadSbiFixtureText();

        const result = await parsePdf(
            new ArrayBuffer(0)
        );

        const paymentReceived =
            result.document.rows.find(
                (row) =>
                    row.values[1] ===
                    "PAYMENT RECEIVED 000000000DUTI6FV1PYEPAD"
            );

        expect(paymentReceived).toBeDefined();
        expect(paymentReceived?.values[0]).toBe(
            "16 Jul 26"
        );
        expect(paymentReceived?.values[2]).toBe(
            "50000.00"
        );
        // A lone C/D is the generic single-letter form of a CR/DR
        // marker - trusted only as the row's final token, directly after
        // its amount (see SINGLE_LETTER_MARKER_RE), never mid-narration.
        // Previously left blank here, which let the normalizer classify
        // every unmarked positive amount - card purchases included - as
        // income.
        expect(paymentReceived?.values[3]).toBe("CR");
        expect(paymentReceived?.values[6]).toBe("50000.00");
    });

    it("correctly parses a real transaction line using a single-letter 'D' marker too", async () => {
        mockState.text = loadSbiFixtureText();

        const result = await parsePdf(
            new ArrayBuffer(0)
        );

        const e2e = result.document.rows.find(
            (row) =>
                row.values[1] ===
                "E2E NETWORKS LIMITED BANGALORE IN (Pay in EMIs)" &&
                row.values[0] === "15 Jul 26"
        );

        expect(e2e).toBeDefined();
        expect(e2e?.values[2]).toBe("17700.00");
        expect(e2e?.values[3]).toBe("DR");
        expect(e2e?.values[5]).toBe("17700.00");
    });

    it("no candidate produced from the full pipeline has an empty payee/description, and all 82 real transactions survive as candidates", async () => {
        mockState.text = loadSbiFixtureText();

        const result = await processPdf(
            new ArrayBuffer(0),
            "CREDIT_CARD_PDF"
        );

        expect(result.candidates).toHaveLength(82);

        const emptyPayeeCandidates =
            result.candidates.filter(
                (candidate) =>
                    !candidate.payee &&
                    !candidate.description
            );

        expect(emptyPayeeCandidates).toHaveLength(0);

        // None of the real transactions should fail validation for a
        // missing payee/description - the one defect that used to
        // reach validation (the bogus summary row) is gone before it
        // gets here at all.
        expect(
            result.validation.errors.some((error) =>
                error.message
                    .toLowerCase()
                    .includes("payee or description")
            )
        ).toBe(false);
    });

    // Structural-discriminator regression: a genuinely non-bank-statement
    // PDF (no date-led transaction lines at all - parsePdf's own
    // extraction finds nothing, so it returns structured: false and
    // falls back to genericDocument's column-split) must still be run
    // through the generic second pass (extractPdfTransactions) via
    // processPdf - only a document pdfParser.ts itself already
    // structured (structured: true) skips it.
    it("still runs the generic fallback extractor for a PDF pdfParser.ts could not structure itself", async () => {
        // No line starts with a date (or a serial number + date), so
        // pdfParser.ts's own structural extraction finds zero
        // transaction blocks and falls back to genericDocument -
        // exactly the "could not structure it" case this branch of
        // processPdf must still hand to extractPdfTransactions.
        mockState.text = [
            "Description\tDate\tDebit\tCredit",
            "ATM Withdrawal\t01/08/2026\t500.00\t",
            "Salary\t05/08/2026\t\t50000.00",
        ].join("\n");

        const parsed = await parsePdf(
            new ArrayBuffer(0)
        );

        expect(parsed.structured).toBe(false);

        const result = await processPdf(
            new ArrayBuffer(0),
            "BANK_CSV"
        );

        expect(result.candidates).toHaveLength(2);
        expect(result.candidates[0]?.amount).toBe(
            500
        );
        expect(result.candidates[1]?.amount).toBe(
            50000
        );
    });
});

describe("PDF parser - real SBI Credit Card statement (parenthetical tax/annotation asides must not be mistaken for the amount)", () => {
    // "16 May 26 FINANCE CHARGE CREDIT (EXCL TAX 0.00) 0.02 C" - the
    // parenthetical's own figure is exactly 0.00, so the old bug (which
    // picked "0.00)" as the amount) failed validation outright: 0.00 is
    // not a valid positive amount, and the real trailing "C" marker was
    // never even reached. This is the row that first surfaced the bug.
    it("FINANCE CHARGE CREDIT: extracts the real trailing amount (0.02), not the parenthetical tax figure (0.00), and produces no validation error", async () => {
        mockState.text = loadSbiFixtureText2();

        const parsed = await parsePdf(
            new ArrayBuffer(0)
        );

        const row = parsed.document.rows.find(
            (r) => r.values[0] === "16 May 26"
        );

        expect(row).toBeDefined();
        expect(row?.values[1]).toBe(
            "FINANCE CHARGE CREDIT (EXCL TAX 0.00)"
        );
        expect(row?.values[2]).toBe("0.02");
        expect(row?.values[2]).not.toBe("0.00");

        const result = await processPdf(
            new ArrayBuffer(0),
            "CREDIT_CARD_PDF"
        );

        const candidate = result.candidates.find(
            (c) =>
                c.description?.startsWith(
                    "FINANCE CHARGE CREDIT",
                ),
        );

        expect(candidate).toBeDefined();
        expect(candidate?.amount).toBe(0.02);
        expect(candidate?.amount).not.toBe(0);

        // No validation error for this row at all - a valid positive
        // amount was found, so the row is a normal, importable
        // transaction like any other.
        expect(
            result.validation.errors.some(
                (error) => error.rowNumber === candidate?.rowNumber,
            ),
        ).toBe(false);

        // Per task scope: C/D is not mapped to a direction by this
        // pipeline (that would be issuer-specific vocabulary) - type
        // is left as whatever the existing universal logic already
        // produces here (undetermined), not asserted as CR/DR.
    });

    // "13 Jun 26 DCC MARKUP FEE DR (EXCL TAX 12.58) 69.90 D" - the
    // parenthetical figure (12.58) is non-zero, so the old bug produced
    // a *silently wrong* amount that still passed validation (a
    // deceptively "ready" row with corrupted data) instead of an
    // obvious error.
    it("DCC MARKUP FEE: extracts the real trailing amount (69.90), not the parenthetical tax figure (12.58)", async () => {
        mockState.text = loadSbiFixtureText2();

        const parsed = await parsePdf(
            new ArrayBuffer(0)
        );

        const row = parsed.document.rows.find(
            (r) => r.values[0] === "13 Jun 26"
                && r.values[1].startsWith("DCC MARKUP FEE"),
        );

        expect(row).toBeDefined();
        expect(row?.values[1]).toBe(
            "DCC MARKUP FEE DR (EXCL TAX 12.58)"
        );
        expect(row?.values[2]).toBe("69.90");
        expect(row?.values[2]).not.toBe("12.58");
    });

    // "15 Jun 26 FIN CHARGE ON RETAIL (EXCL TAX 2299.82) 12,776.76 D" -
    // same bug, largest of the three affected figures, also
    // comma-formatted in the source text.
    it("FIN CHARGE ON RETAIL: extracts the real trailing amount (12776.76), not the parenthetical tax figure (2299.82)", async () => {
        mockState.text = loadSbiFixtureText2();

        const parsed = await parsePdf(
            new ArrayBuffer(0)
        );

        const row = parsed.document.rows.find(
            (r) => r.values[0] === "15 Jun 26"
                && r.values[1].startsWith("FIN CHARGE ON RETAIL"),
        );

        expect(row).toBeDefined();
        expect(row?.values[1]).toBe(
            "FIN CHARGE ON RETAIL (EXCL TAX 2299.82)"
        );
        expect(row?.values[2]).toBe("12776.76");
        expect(row?.values[2]).not.toBe("2299.82");
    });

    it("never selects any of the three parenthetical annotation figures (0.00, 12.58, 2299.82) as a transaction amount anywhere in the document", async () => {
        mockState.text = loadSbiFixtureText2();

        const parsed = await parsePdf(
            new ArrayBuffer(0)
        );

        const amounts = parsed.document.rows.map(
            (r) => r.values[2]
        );

        expect(amounts).not.toContain("0.00");
        expect(amounts).not.toContain("12.58");
        expect(amounts).not.toContain("2299.82");
    });

    it("preserves the valid accounting-style negative-amount parenthesis form, e.g. '(500.00)', as a single self-contained amount", async () => {
        mockState.text = [
            "16 May 26 REFUND ADJUSTMENT (500.00) C",
        ].join("\n");

        const parsed = await parsePdf(
            new ArrayBuffer(0)
        );

        expect(parsed.document.rows).toHaveLength(1);
        expect(
            parsed.document.rows[0]?.values[1]
        ).toBe("REFUND ADJUSTMENT");
        expect(
            parsed.document.rows[0]?.values[2]
        ).toBe("500.00");
    });
});

// The real statement in fixture 1 is the one whose import preview showed
// 6 errors: row 22 "Transaction type could not be determined" and
// balance mismatches on rows 31, 35, 39, 65 and 72. Every affected line
// is an international transaction printing its original foreign-currency
// amount in the narration before the billed amount:
//   "15 Jul 26 BREEZEHOST BREEZEHOST.IO TX 4.32 USD 415.79 D"
// findTail read "USD" as a currency PREFIX of 415.79 and kept walking, so
// 4.32 became the amount and "415.79 D" a negative running balance - on
// a statement that prints no running balance at all. Directions were
// then guessed from those fake balances (row 22, the first, had nothing
// to compare with). The fix is the generic notation rule in
// readCodeBeforeCell - nothing here is issuer-specific.
describe("PDF parser - original foreign-currency amount printed in the narration", () => {
    const FOREIGN_LINE_RE =
        /^\d{2} [A-Z][a-z]{2} 26 (.+ [\d,]+\.\d{2} [A-Z]{3}) ([\d,]+\.\d{2}) D$/;

    // [row, description, billed amount] straight from the fixture text.
    // The preview's rows 22, 31, 35, 39, 65 and 72 - two higher now that
    // the two undated fee lines after row 20 are no longer dropped.
    const failingRows: [number, string, string][] = [
        [24, "BREEZEHOST BREEZEHOST.IO TX 4.32 USD", "415.79"],
        [33, "PADDLE.NET* VPSDIME London GB 8.26 USD", "796.37"],
        [37, "BREEZEHOST BREEZEHOST.IO TX 6.17 USD", "594.87"],
        [41, "BREEZEHOST BREEZEHOST.IO TX 6.17 USD", "595.90"],
        [67, "BREEZEHOST BREEZEHOST.IO TX 10.29 USD", "981.36"],
        [74, "BREEZEHOST BREEZEHOST.IO TX 9.14 USD", "872.50"],
    ];

    it.each(failingRows)(
        "row %i: the billed amount is the amount, D is its direction, the foreign amount stays in the narration, no balance",
        async (rowNumber, description, amount) => {
            mockState.text = loadSbiFixtureText();

            const parsed = await parsePdf(new ArrayBuffer(0));
            const row = parsed.document.rows.find(
                (r) => r.rowNumber === rowNumber,
            );

            // Description | Amount | Type | Reference | Debit | Credit | Balance
            expect(row?.values.slice(1)).toEqual([
                description,
                amount,
                "DR",
                "",
                amount,
                "",
                "",
            ]);
        },
    );

    it("the full pipeline: no type or balance errors, every foreign-currency line is an expense of its billed amount", async () => {
        mockState.text = loadSbiFixtureText();

        const result = await processPdf(
            new ArrayBuffer(0),
            "CREDIT_CARD_PDF",
        );

        expect(result.validation.errors).toEqual([]);
        expect(result.candidates.every((c) => c.type)).toBe(true);
        // The statement prints no running balance, so there is nothing
        // to reconcile - and no fake balance to reconcile against.
        expect(result.candidates.every((c) => c.balance === null)).toBe(true);
        expect(result.balanceReconciliation.checkedRows).toBe(0);

        const foreignLines = loadSbiFixtureText()
            .split(/\r?\n/)
            .map((line) => line.match(FOREIGN_LINE_RE))
            .filter((match) => match !== null);

        expect(foreignLines).toHaveLength(16);

        // In document order - descriptions repeat with different amounts.
        expect(
            result.candidates
                .filter((c) => / [\d,]+\.\d{2} [A-Z]{3}$/.test(c.description ?? ""))
                .map((c) => [c.description, c.type, c.amount]),
        ).toEqual(
            foreignLines.map(([, description, billed]) => [
                description,
                "expense",
                Number(billed.replace(/,/g, "")),
            ]),
        );
    });

    it("every transaction line's printed amount and C/D direction is imported exactly once, as printed - nothing altered, nothing dropped", async () => {
        mockState.text = loadSbiFixtureText();

        const result = await processPdf(
            new ArrayBuffer(0),
            "CREDIT_CARD_PDF",
        );

        // Independent of the parser: the trailing "<amount> C|D" of every
        // line in the source text that describes a movement - dated or
        // not - i.e. a description followed by a C/D-marked amount.
        const printed = loadSbiFixtureText()
            .split(/\r?\n/)
            .map((line) =>
                line.match(/^(?:\d{2} [A-Z][a-z]{2} 26 )?[A-Za-z].* ([\d,]+\.\d{2}) ([CD])$/),
            )
            .filter((match) => match !== null)
            .map(([, amount, marker]) =>
                `${marker === "C" ? "income" : "expense"} ${Number(amount.replace(/,/g, "")).toFixed(2)}`,
            )
            .sort();

        const imported = result.candidates
            .map((c) => `${c.type} ${c.amount?.toFixed(2)}`)
            .sort();

        expect(printed).toHaveLength(82);
        expect(imported).toEqual(printed);

        // The statement's own Account Summary: "Payments, Reversals &
        // other Credits" 4,50,122.76; "Purchases & Other Debits"
        // 4,62,272.77 + "Fee, Taxes & Interest Charges" 5,727.67.
        expect(totalOf(result.candidates, "income")).toBe(450122.76);
        expect(totalOf(result.candidates, "expense")).toBe(468000.44);
    });

    it("the previous statement (fixture 2) has the same shape and is read the same way", async () => {
        mockState.text = loadSbiFixtureText2();

        const result = await processPdf(
            new ArrayBuffer(0),
            "CREDIT_CARD_PDF",
        );

        expect(
            result.candidates.find(
                (c) => c.transactionDate === "2026-05-16" &&
                    c.description === "BREEZEHOST BREEZEHOST.IO TX 6.00 USD",
            ),
        ).toMatchObject({ type: "expense", amount: 576.91, balance: null });

        expect(
            result.validation.errors.filter(
                (e) => e.field === "type" || e.field === "balance",
            ),
        ).toEqual([]);
    });
});

describe("PDF parser - a currency code between two amounts follows the row's own notation", () => {
    async function parseLine(line: string) {
        mockState.text = line;

        const parsed = await parsePdf(new ArrayBuffer(0));

        return parsed.document.rows[0]?.values;
    }

    // Date | Description | Amount | Type | Reference | Debit | Credit | Balance
    it("prefix notation on both cells: amount + balance, as before", async () => {
        expect(
            await parseLine("01/07/2026 UPI TEST SHOP INR 350.00 INR 9,650.00"),
        ).toMatchObject({ 1: "UPI TEST SHOP", 2: "350.00", 7: "9650.00" });
    });

    it("suffix notation on both cells: amount + balance, as before", async () => {
        expect(
            await parseLine("01/07/2026 UPI TEST SHOP 350.00 INR 9,650.00 INR"),
        ).toMatchObject({ 1: "UPI TEST SHOP", 2: "350.00", 7: "9650.00" });
    });

    it("an amount in a different currency is narration, even when prefixed", async () => {
        expect(
            await parseLine("15 Jul 26 TEST HOST USD 4.32 INR 415.79 D"),
        ).toMatchObject({ 1: "TEST HOST USD 4.32", 2: "415.79", 3: "DR", 7: "" });
    });

    it("a suffixed amount before an un-coded cell is narration", async () => {
        expect(
            await parseLine("15 Jul 26 TEST HOST 4.32 USD 415.79 D"),
        ).toMatchObject({ 1: "TEST HOST 4.32 USD", 2: "415.79", 3: "DR", 7: "" });
    });
});

describe("balance validation still catches genuine mismatches", () => {
    it("a statement WITH a running balance: a foreign-currency narration amount never hides a wrong balance", async () => {
        mockState.text = [
            "Date Description Amount Balance",
            "Opening Balance 1,000.00",
            "01/07/2026 TEST SHOP 100.00 DR 900.00",
            // Billed 50.00 should leave 850.00 - the statement says 800.00.
            "02/07/2026 TEST HOST 4.32 USD 50.00 DR 800.00",
            "03/07/2026 TEST REFUND 25.00 CR 825.00",
        ].join("\n");

        const result = await processPdf(
            new ArrayBuffer(0),
            "BANK_PDF",
        );

        expect(
            result.candidates.map((c) => [c.description, c.type, c.amount, c.balance]),
        ).toEqual([
            ["TEST SHOP", "expense", 100, 900],
            ["TEST HOST 4.32 USD", "expense", 50, 800],
            ["TEST REFUND", "income", 25, 825],
        ]);

        // Row 2 is flagged with its real amount - not altered to fit.
        expect(result.balanceReconciliation.mismatches).toMatchObject([
            { rowNumber: 2, amount: 50, expectedBalance: 850, statementBalance: 800, kind: "amount" },
        ]);
        expect(result.balanceReconciliation.checkedRows).toBe(2);
    });
});

// Both real statements print two fee/tax lines with no date of their own
// directly under the statement-date finance-charge row:
//   15 Aug 26 FIN CHARGE ON RETAIL (EXCL TAX 690.07) 3,833.71 D
//   FORGN CURR MARKUP DB (EXCL TAX 171.11) 950.58 D
//   IGST DB @ 18.00% 873.72 D
//   TRANSACTIONS FOR <CARDHOLDER>
// extractBankTransactions only ever started a row at a dated line, so
// both were skipped without a trace - while the preview still showed 0
// errors. They are now undated postings (see isUndatedPosting) sharing
// the date of the row they are printed under.
describe("PDF parser - undated fee/tax lines are never dropped", () => {
    // Date | Description | Amount | Type | Reference | Debit | Credit | Balance
    it("August: rows 21 and 22 are the two fee lines, dated like row 20 above them; rows 20 and 23 are unchanged", async () => {
        mockState.text = loadSbiFixtureText();

        const parsed = await parsePdf(new ArrayBuffer(0));
        const rows = new Map(
            parsed.document.rows.map((r) => [r.rowNumber, r.values]),
        );

        expect(rows.get(20)).toEqual(["15 Aug 26", "FIN CHARGE ON RETAIL (EXCL TAX 690.07)", "3833.71", "DR", "", "3833.71", "", ""]);
        expect(rows.get(21)).toEqual(["15 Aug 26", "FORGN CURR MARKUP DB (EXCL TAX 171.11)", "950.58", "DR", "", "950.58", "", ""]);
        expect(rows.get(22)).toEqual(["15 Aug 26", "IGST DB @ 18.00%", "873.72", "DR", "", "873.72", "", ""]);
        expect(rows.get(23)).toEqual(["15 Jul 26", "E2E NETWORKS LIMITED BANGALORE IN (Pay in EMIs)", "17700.00", "DR", "", "17700.00", "", ""]);
    });

    it("June: the two equivalent fee lines are rows too, and both statements' totals now equal their own Account Summary", async () => {
        mockState.text = loadSbiFixtureText2();

        const result = await processPdf(
            new ArrayBuffer(0),
            "CREDIT_CARD_PDF",
        );

        const fees = result.candidates.filter((c) =>
            /^(FORGN CURR MARKUP DB|IGST DB)/.test(c.description ?? ""),
        );

        expect(fees.map((c) => [c.transactionDate, c.description, c.type, c.amount])).toEqual([
            ["2026-06-15", "FORGN CURR MARKUP DB (EXCL TAX 69.48)", "expense", 386.01],
            ["2026-06-15", "IGST DB @ 18.00%", "expense", 2381.88],
        ]);

        expect(result.validation.errors).toEqual([]);

        // June Account Summary: credits 2,50,075.52; purchases
        // 1,85,582.27 + fees, taxes & interest 15,614.55.
        expect(totalOf(result.candidates, "income")).toBe(250075.52);
        expect(totalOf(result.candidates, "expense")).toBe(201196.82);
    });
});
